### ISSUE TITLE
Scrolling when swipe direction is defined does not work

### ISSUE THREAD

**Issue by jvliwanag** [GSTJ/react-native-magic-modal#111]
**Describe the bug**
Scrollviews within modals do not work with the default modal settings, wherein `swipeDirection` is not set to undefined. This is a documented up front, but it would be great to still allow scrolling on relevant modal sections, but still be able to dismiss the modal by swiping on the non scrollable areas.

**Expected behavior**
Scroll on scrollable areas. Dismiss when swiping on the chosen direction for the non-scrollable areas.

**Comment by GSTJ** [comment]
As mentioned, this is documented and unplanned as of right now. I'll accept PRs implementing it, but it's not on my roadmap to compete with Gorham's implementation for now due to the messy nature of touch events.
