### ISSUE TITLE
Modal is not displayed on Android

### ISSUE THREAD

**Issue by mkloouo** [GSTJ/react-native-magic-modal#119]
**Describe the bug**
Android emulator device does not show the modal at all.

**To Reproduce**
1. Generate `react-native@0.75.3` project 
2. Add `react-native-magic-modal` + peer deps (`react-native-reanimated@~3.15.0` and `react-native-gesture-handler@~2.18.1`)
3. Configure portal etc
4. Show view with set width and height and set white BG to make sure to see some kind of modal
5. See it on iOS Simulator/real device
6. Do not see it on the Android device

**Expected behavior**
See the modal on the Android device

**Screen capture**

[test on iOS](https://github.com/user-attachments/assets/be754248-1329-4f3d-9e2f-d81e5f95b7bc)
[test on android.webm](https://github.com/user-attachments/assets/c1099b13-60ff-47a9-8637-47838a0e1077)

**Smartphone (please complete the following information):**
 - Device: Medium Table Emulator
 - OS: Android
 - Version 35

**Additional context**
I tried figuring out and it seems from the logs that everything renders, just does not appear on the screen.
Changing `zIndex` to `1` on the surrounding View in `index.cjs` seems to fix the issue, but that's not a solution, just a hint where to look

 
[zindex 1 android.webm](https://github.com/user-attachments/assets/f9b1da1b-c9eb-4bcd-9b14-7aabc7be2f18)

**Comment by GSTJ** [comment]
I've created a branch with the same dependencies you mentioned, but I was not able to repro the issue:

https://github.com/user-attachments/assets/1c86a3b4-a701-41b3-832d-d19e79efb8de

Branch: chore/reproduce-issue

Can you try it on my branch? I would appreciate a branch that I can clone so that I can see this in action before following up with a fix.

**Comment by mkloouo** [comment]
@GSTJ, unable to repro on your branch as well, please try to reproduce on a bare app setup with react-native@0.75.3
I also think it's due to some changes in the react-native, mainly the way that they default View props on Android, I think.

I was preparing an example for you in the `chore/reproduce-issue` branch, but since I am not familiar with pnpm and your project in general, it's taking way too much time.

**Comment by mkloouo** [comment]
@GSTJ figured out `pnpm`, going to push to the same branch soon

**Comment by mkloouo** [comment]
@GSTJ notifying that was not able to repro on bare with the specified react-native version, trying to figure out the deps in the project I am working on.

**Comment by GSTJ** [comment]
Thanks!

Might be where your magic portal is positioned somehow, try moving it to render in the front of everything.

iOS has a full window overlay that brings it to the front always, Android needs the portal to be correctly positioned.

**Comment by mkloouo** [comment]
I love how I just figured it out and got back to tell you that my portal was before NavigationContainer :)
All works now, whoops 😓

**Comment by cristea2017** [comment]
after upgrading to  react native 0.78.0, i got the same issue 

my old code  that doesn't work 
```<GestureHandlerRootView style={theme.flex}>
      <MagicModalPortal />
      <NetworkMonitorService />
      <BottomSheetModalProvider>
        <MagicSheetPortal {...magicSheedProps} />
        <AppNavigation />
      </BottomSheetModalProvider>
      <DropdownAlertComponent />
      <MagicModalPortal />
    </GestureHandlerRootView>
```
I moved the MagicModalPortal before navigation and still doesn't work, but when moved it at the end it works
 
```<GestureHandlerRootView style={theme.flex}>
      <NetworkMonitorService />
      <BottomSheetModalProvider>
        <MagicSheetPortal {...magicSheedProps} />
        <AppNavigation />
      </BottomSheetModalProvider>
      <DropdownAlertComponent />
//should be last child
      <MagicModalPortal />
    </GestureHandlerRootView>
```

https://github.com/user-attachments/assets/b81feea9-0507-4797-89a2-8750cae33074
