### ISSUE TITLE
How it should work with react-navigation?

### ISSUE THREAD

**Issue by rendomnet** [GSTJ/react-native-magic-modal#120]
**MagicModalPortal** should be inside **NavigationContainer** or beside it?

This is correct, App.tsx?
```
    <GestureHandlerRootView style={{flex: 1}}>
      <NavigationContainer>
        <Router />          
      </NavigationContainer>
      <MagicModalPortal />
    </GestureHandlerRootView>
```

**Comment by GSTJ** [comment]
MagicModalPortal needs to be rendered on top of all app content and inside Gesture Handler.

Placing it as the last component inside Gesture Handler is recommended.

If your approach of putting it inside Navigation works and throws no errors, you might be able to access useNavigation inside modals as a bonus. Though,but haven't tested this use-case yet.

Let me know if it works for you.
