### ISSUE TITLE
Not compatible with Expo SDK 52

### ISSUE THREAD

**Issue by julius-lae** [GSTJ/react-native-magic-modal#121]
**Describe the bug**
When you upgrade to Expo SDK 52 this module is not working anymore. When you start the app, it shows the error `Invariant Violation: Tried to register two views with the same name RNSScreen
`

**To Reproduce**
1. Create a project with `create-expo-app `
2. Install and implement react-native-magic-modal
3. Start the app and open it with Expo Go App

**Expected behavior**
The app should start without the error message and when you execute `magicModal.show`, it should display the modal.

**Dependencies**
"@expo/vector-icons": "^14.0.2",
    "@react-navigation/bottom-tabs": "^7.0.0",
    "@react-navigation/native": "^7.0.0",
    "expo": "~52.0.18",
    "expo-blur": "~14.0.1",
    "expo-constants": "~17.0.3",
    "expo-font": "~13.0.1",
    "expo-haptics": "~14.0.0",
    "expo-linking": "~7.0.3",
    "expo-router": "4.0.11",
    "expo-splash-screen": "~0.29.18",
    "expo-status-bar": "~2.0.0",
    "expo-symbols": "~0.2.0",
    "expo-system-ui": "~4.0.6",
    "expo-web-browser": "~14.0.1",
    "react": "18.3.1",
    "react-dom": "18.3.1",
    "react-native": "0.76.5",
    "react-native-gesture-handler": "~2.20.2",
    "react-native-magic-modal": "^5.1.20",
    "react-native-reanimated": "~3.16.1",
    "react-native-safe-area-context": "4.12.0",
    "react-native-screens": "~4.1.0",
    "react-native-web": "~0.19.13",
    "react-native-webview": "13.12.5"

**Comment by spartanlync** [comment]
Exact same issue in my project after adding

import { MagicModalPortal } from "react-native-magic-modal";

export default function TabTwoScreen() {
  // Render UI
  return (
    <GestureHandlerRootView style={styles.container}>
      <SetupWizard />
      <MagicModalPortal />
    </GestureHandlerRootView>
  );
}

**Comment by GSTJ** [comment]
Thanks for reporting! Can you install `react-native-magic-modal@experimental` and see if it solves your issue?

**Comment by GSTJ** [comment]
Reopening to keep track.

**Comment by spartanlync** [comment]
> Thanks for reporting! Can you install `react-native-magic-modal@latest` and see if it solves your issue?

Hello, I can confirm that "react-native-magic-modal@experimental" resolved the issue in my project.

Thanks

**Comment by GSTJ** [comment]
Nice! Closing. Thanks - feel free to use latest as the fix is already merged.
