### ISSUE TITLE
Backdrop fills on half in landscape orientation

### ISSUE THREAD

**Issue by xdarkleonx** [GSTJ/react-native-magic-modal#27]
In portrait orientation backdrop covers all width and works fine, but when you change to landscape backdrop is covering half.

![Screenshot_16940](https://github.com/GSTJ/react-native-magic-modal/assets/32865363/cd14d3d4-a788-4c27-be52-88d4f106e2c4)

```
modalConfig = {
  animationIn: 'fadeIn',
  animationOut: 'fadeOut',
  coverScreen: false,
  swipeDirection: null,
}

magicModal.show(
  <ActionMenu
     style={mainLayout.modal}
     label={t('diaryMenu')}
     items={actions}
     dayItems={fastInsertItems}
      onValueChange={() => magicModal.hide()}
  />
  , modalConfig
)
```

I found workaround and add deviceWidth to modalConfig. But i think it should be work without setting manually width to modal.

**Comment by GSTJ** [comment]
Fixed!
