### ISSUE TITLE
[Feature Request] A way to disable dismiss swipe

### ISSUE THREAD

**Issue by yepMad** [GSTJ/react-native-magic-modal#7]
**Is your feature request related to a problem? Please describe.**
I use modals that I need the user to interact with. It is very interesting to me that the user cannot ignore it with swipe.

**Describe the solution you'd like**
Boolean "isSwipeable" to enable/disable swipe.

**Describe alternatives you've considered**
Place a gesture handler over the entire component to inhibit user gestures. But it affects the buttons.

**Comment by yepMad** [comment]
Fact: "swipeDirection: undefined" inhibits Swipe, but if the user still has access to the transparent black overlay on the back, clicking it dismisses the modal.

**Comment by yepMad** [comment]
`
    magicModal.show(ExampleModal, {
      swipeDirection: undefined,
      onBackdropPress: () => null,
    });
`

Solve the problem. Sorry, I really need sleep lol. Anyway, I'll leave this FR grip, I think it might be something interesting.

**Comment by GSTJ** [comment]
That's really it! The config params will accept most properties from the original react-native-modal.

I'll keep the issue open untill I add more examples for those use-cases.
